require("plugins.plugins")

require("plugins.treesitter")
require("plugins.neoscroll")
require("plugins.telescope")
require("plugins.colorscheme")
require("plugins.scratchpad")
require("plugins.lspconfig")
require("plugins.nvim-compe")
require("plugins.lspkind")
require("plugins.statusline")
require("plugins.colorizer")
require("plugins.nvim-tree")
require("plugins.nvim-web-devicons")
require("plugins.comments")
require("plugins.formatter")
